usr/include/postgresql/internal/*
usr/include/postgresql/libpq-fe.h
usr/include/postgresql/libpq-events.h
usr/include/postgresql/libpq/libpq-fs.h
usr/include/postgresql/pg_config*.h
usr/include/postgresql/postgres_ext.h
usr/lib/*/pkgconfig/libpq.pc
usr/lib/*/libpgcommon.a
usr/lib/*/libpgport.a
usr/lib/*/libpq.a
usr/lib/*/libpq.so
usr/lib/postgresql/9.4/bin/pg_config usr/bin
usr/share/locale/*/LC_MESSAGES/pg_config-9.4.mo
usr/share/postgresql/9.4/man/man1/pg_config.1.gz /usr/share/man/man1
